In [ ]:
#--------------hypothesis-test------------
# Close Price - VWAP
# Buy Reco – More than 60
# Upside > 0 
# PE Ratio – 0 and above
# % Upside -5.00 and above

1."create buy/sell column in dataset"
2."select predictor column  (close price,profit ,etc )"
3."contingency table"
4." perform chi-square test on decision vs target column"

In [4]:
#example

import pandas as pd
data = pd.read_csv("./50_Startups.csv")
ct=pd.crosstab(data['Profit'],data['State'])
ct

State      California  Florida  New York
Profit
14681.40            1        0         0
35673.41            0        0         1
42559.73            1        0         0
49490.75            0        1         0
64926.08            0        0         1
65200.33            1        0         0
69758.98            0        0         1
71498.49            1        0         0
77798.83            0        1         0
78239.91            1        0         0
81005.76            1        0         0
81229.06            0        0         1
89949.14            1        0         0
90708.19            0        1         0
96479.51            0        0         1
96712.80            1        0         0
96778.92            0        1         0
97427.84            1        0         0
97483.56            0        0         1
99937.59            0        1         0
101004.64           0        0         1
103282.38           0        1         0
105008.31           0        0         1
105733.54           0        1         0
107404.34           1        0         0
108552.04           0        0         1
108733.99           0        1         0
110352.25           0        1         0
111313.02           0        0         1
118474.03           1        0         0
122776.86           0        0         1
124266.90           0        1         0
125370.37           0        0         1
126992.93           1        0         0
129917.04           0        0         1
132602.65           0        1         0
134307.35           1        0         0
141585.52           0        1         0
144259.40           1        0         0
146121.95           0        1         0
149759.96           1        0         0
152211.77           0        0         1
155752.60           0        1         0
156122.51           1        0         0
156991.12           0        0         1
166187.94           0        1         0
182901.99           0        0         1
191050.39           0        1         0
191792.06           1        0         0
192261.83           0        0         1

In [5]:
from scipy.stats import chi2_contingency
stat,pvalue,_,expected_R= chi2_contingency(ct)

if pvalue <= 0.05:
    print("Conditions performing well")
else:
    print("Change the conditions")

Change the conditions

In [8]:
expected_R.shape
stat

99.99999999999999

In [10]:
pvalue

0.42486667820276625